runtime: go112

handlers:
- url: /
  static_files: index.html
  upload: index.html
- url: /help.html
  static_files: help.html
  upload: help.html
- url: /style.css
  static_files: style.css
  upload: style.css
- url: /favicon.ico
  static_files: favicon.ico
  upload: favicon.ico
- url: /examples
  static_dir: examples
  mime_type: "text/plain; charset=utf-8"
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

